apiVersion: v1
kind: Pod
metadata:
  name: clientPod
  labels:
    name: web
spec:
  containers:
    - name: client
      image: ppdraga/multi-client
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3000
